name: frontend
description: A Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 0.14.0+3
  hive: 2.0.4
  http: 0.13.1
  json_serializable: 4.1.3
  jwt_decoder: 2.0.1
  auto_route: 2.2.0
  intl: 0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.3
  auto_route_generator: 2.1.0
  build_runner: 2.0.4

flutter:
  generate: true
  uses-material-design: true
